type DimensionsType = {
	[key: string]: number;
};

export const DIMENSIONS: DimensionsType = {
	What: 0.2,
	'How Much': 0.2,
	Contribution: 0.2,
	Who: 0.2,
	Risk: 0.2
};

type QuestionType = {
	question: string;
	responses: {
		[key: string]: number;
	};
	weight: number;
	dimension: string;
};

export const QUESTIONS: QuestionType[] = [
	{
		question: 'toc-design',
		dimension: 'What',
		weight: 0.5,
		responses: {
			"1) The project has a comprehensive and periodically revisited ToC that describes the intervention's results and impact ambitions in the short, mid, and long terms.": 3,
			"2) The project has a comprehensive ToC that outlines intended outcomes and impact ambitions in the short, mid, and long terms, but that isn't periodically reviewed.": 2,
			'3) The project does not have a comprehensive ToC that outlines intended outcomes and impact ambitions.': 0,
			'4) Unsure': 0
		}
	},
	{
		question: 'beneficiary-surveys',
		dimension: 'What',
		weight: 0.5,
		responses: {
			'1) The project regularly surveys a statistical sample of former direct beneficiaries to collect data  on the extent (e.g., depth and duration of impact, relapse rates, etc.) and relevance of the impact generated by the intervention.': 3,
			'2) The project intermittently surveys former direct beneficiaries to collect data on the extent (e.g., depth and duration of impact, relapse rate, etc.) and relevance of the impact generated by the intervention and may not use statistical sampling or standardized survey tools to gather this feedback.': 2,
			'3) The project does not survey former direct beneficiaries.': 0,
			'4) Unsure': 0
		}
	},
	{
		question: 'selected-outcome-scale',
		dimension: 'How Much',
		weight: 0.2,
		responses: {
			'100,000 or more': 2,
			'50,000-100,000': 2,
			'10,000-50,000': 3,
			'2,500-10,000': 2,
			'Less than 2,500': 1
		}
	},
	{
		question: 'baseline-and-endline-assessments',
		dimension: 'How Much',
		weight: 0.45,
		responses: {
			'1) The project consistently applies an externally validated methodology at baseline and endline to identify different segments of participants, accurately monitor and reflect their situation, and improve project design.': 3,
			'2) The project intermittently surveys the beneficiary population at baseline and endline, but the methodology was not externally validated.': 2,
			'3) The project does not survey the beneficiary population at baseline and/or endline': 0,
			'4) Unsure': 0
		}
	},
	{
		question: 'selected-outcome-duration',
		dimension: 'How Much',
		weight: 0.35,
		responses: {
			'10+ years': 3,
			'3-10 years': 3,
			'1-3 years': 2,
			'6-12 months': 1,
			'0-6 months': 1,
			Unsure: 0
		}
	},
	{
		question: 'counterfactual',
		dimension: 'Contribution',
		weight: 0.4,
		responses: {
			'1) Yes, by using an Experimental method (e.g., RCT)': 3,
			'2) Yes, by using a Quasi-Experimental method (e.g., difference-in-difference, matched comparisons, etc.)': 3,
			'3) Yes, by using a Non-experimental method (e.g., logically constructed counterfactual)': 2,
			"4) No, we haven't assessed a counterfactual for this outcome": 0,
			'5) Unsure': 0
		}
	},
	{
		question: 'external-contributions',
		dimension: 'Contribution',
		weight: 0.3,
		responses: {
			"1) The project continuously tracks and engages other programs working in the same landscape and/or with the same group of beneficiaries to assess their potential contribution to the intervention's outcomes.": 3,
			"2) The project sporadically tracks and engages other programs working in the same landscape and/or with the same group of beneficiaries to assess their potential contribution to the intervention's outcomes.": 2,
			"3) The project does not track or engage other programs working in the same landscape and/or with the same group of beneficiaries, and is unaware of their contribution to the intervention's outcomes.": 0,
			'4) Unsure': 0
		}
	},
	{
		question: 'external-events',
		dimension: 'Contribution',
		weight: 0.3,
		responses: {
			'1) The project has a methodology for tracking and accounting for external events in the communities where it operates and integrates these events into its reporting of project impacts': 3,
			'2) The project is aware of external events and how they may affect project outcomes, but does not regularly track or account for these events in its reporting of project impacts': 2,
			'3) The project does not track external events and does not account for them in its reporting': 0,
			'4) Unsure': 0
		}
	},
	{
		question: 'beneficiaries-household-data',
		dimension: 'Who',
		weight: 0.5,
		responses: {
			'1) The project systematically collects household-level data from all direct beneficiaries, including details of the service/intervention and beneficiary demographics. In addition, protocols for data quality checks, privacy protection, and data security are well-established and documented': 3,
			'2) The project directly engages beneficiaries, but does not systematically collect full project and demographic data from all beneficiaries. Data quality checks, privacy protection, and data security protocols may need to be further developed and documented.': 2,
			'3) The project does not directly engage beneficiaries and/or does not have the ability to gather project and demographic data on all beneficiaries.': 0,
			'4) Unsure': 0
		}
	},
	{
		question: 'beneficiaries-consent',
		dimension: 'Who',
		weight: 0.5,
		responses: {
			"1) The organization has a clear and consistent process for seeking free and informed consent from beneficiaries or their representatives, ensuring that they fully understand the project's goals and potential impacts before implementation starts.": 3,
			'2) The organization seeks free and informed consent from beneficiaries or their representatives before the intervention starts, but does not have a consistent and standardized process in place.': 2,
			'3) The organization does not seek consent from beneficiaries or their representatives before the start of its interventions.': 0,
			'4) Unsure': 0
		}
	},
	{
		question: 'intended-unintended-outcomes',
		dimension: 'Risk',
		weight: 0.35,
		responses: {
			'1) The project comprehensively assesses all intended and unintended outcomes and forecasts both positive and negative outcomes in its ToC. Moreover, the reporting includes both positive and negative outcomes, providing an accurate assessment of the impact generated by the intervention.': 3,
			'2) The project only forecasts positive or intended outcomes in its ToC, but provides open formats for receiving negative feedback and integrating any unintended consequences into assessments and reporting. The reporting might include some unintended outcomes and provides a moderate assessment of the impact generated by the intervention.': 2,
			'3) The project does not differentiate between intended and unintended outcomes. The reporting does not include negative outcomes and provides an inaccurate assessment of the impact generated by the intervention.': 0,
			'4) Unsure': 0
		}
	},
	{
		question: 'periodic-reporting',
		dimension: 'Risk',
		weight: 0.3,
		responses: {
			"1) The project uses a standardized methodology to periodically report on the outcomes of its interventions to external and internal stakeholders. This methodology is aligned with the project's ToC.": 3,
			"2) The project periodically reports on the outcomes of its interventions to external and internal stakeholders. But the methodology may not be standardized and/or lack alignment with the project's ToC.": 2,
			'3) The project does not consistently/periodically report on the outcomes of its interventions to external and internal stakeholders.': 0,
			'4) Unsure': 0
		}
	},
	{
		question: 'partner-engagement',
		dimension: 'Risk',
		weight: 0.35,
		responses: {
			'1) The project directly engages local partners and/or community leaders to implement the project. There are frequent and open communications with local partners to integrate their feedback into project design and ensure resources are effectively allocated': 3,
			'2) The project does not work directly with local organizations or partners but regularly engages local leaders or community members to gather their feedback': 2,
			'3) The project does not engage local partners or leaders and/or does not gather feedback from them': 0,
			'4) Unsure': 0
		}
	}
];
